### PR TITLE
Migrating application to GCP

### PR DESCRIPTION
**Pull request by rodrigopaulino**

### CODE REVIEW

**Comment by linolaoj** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by linolaoj** [comment]
Merged :+1: 
Thanks!

**Comment by rodrigopaulino** [comment]
@linolaoj just noticed that tests are failing due to the change of app server. Will look into that this week.

**Comment by linolaoj** [comment]
@rodrigopaulino, already fixed on  68b8f78432677c1c873ac705b6895f0e91815108 :+1:

**Comment by rodrigopaulino** [comment]
This will actually break the `gw appengineRun`. Did you test it?

**Comment by linolaoj** [comment]
Yes, I tested , it works :)

**Pull request merged**
